fix: parallel repair
celestiaorg/rsmt2d pull request #131
Opened 2022-09-28 13:22 UTC by rahulghangas

`solveCrosswordRow` sets cells for the crossword which are accessed in `solveCrosswordColumn`, which means that both being run in parallel has a race condition.

This PR resolves this by running all `solveCrosswordRow` in parallel and waiting for all these calls to finish before executing all `solveCrosswordColumn` calls in parallel

- [x] Fixes #123

2022-09-28 13:27 UTC, rahulghangas commented
Linking conversation from #129 and #130

> This seems to imply the reason why parallelisation_crosswordloop didn't work was not because of the decoder, but because of rsmt2d. In that case how come it worked with infectious but not leopard or klauspost?

Infectious was failing on my machine, although sporadically. I think it was just the race condition at play. 

> Blocking column repair until row repair is complete means that we aren't maximizing the parallelisation that we can do. Is there another way to fix this, eg add mutexes for setting cells?

I don't think so, the race condition is between reading and writing of cells. For eg. `solveCrosswordRow` is setting cells [here](https://github.com/celestiaorg/rsmt2d/pull/130/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L176) while the same cell is being read by `solveCrosswordCol` [here](https://github.com/celestiaorg/rsmt2d/pull/130/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L212). iiuc, the cell must set with the rebuilt shares before being read

2022-09-28 13:39 UTC, musalbas commented on extendeddatacrossword.go
> +				wg.Wait()
Instead of adding wait groups and subroutines for inactive tasks would it be simpler if we just had two for loops, one for rows and one for columns?

2022-09-28 13:40 UTC, musalbas commented
>I don't think so, the race condition is between reading and writing of cells. For eg. solveCrosswordRow is setting cells [here](https://github.com/celestiaorg/rsmt2d/pull/130/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L176) while the same cell is being read by solveCrosswordCol [here](https://github.com/celestiaorg/rsmt2d/pull/130/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L212). iiuc, the cell must set with the rebuilt shares before being read

Makes sense - if the data is malicious then we might end up setting different data into the same cell

2022-09-28 15:22 UTC, rahulghangas commented
All data races have been fixed. #128 needs to be merged for tests to pass

@musalbas @adlerjohn please review

2022-09-28 15:25 UTC, musalbas commented
Can you explain why row/col mutexes has been added? From the original description of the race condition this doesn't seem necessary

2022-09-28 15:33 UTC, rahulghangas commented
> Can you explain why row/col mutexes has been added? From the original description of the race condition this doesn't seem necessary

After setting a cell with the rebuilt share, the entire row/col must be read to verify if the entire row has been set or not, [ref](https://github.com/celestiaorg/rsmt2d/pull/131/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L176-L182)

While the entire row is being read, another go routine might be writing to the same row (just a different cell), which might lead to spurious results

2022-09-28 15:38 UTC, rahulghangas commented
`solveCrosswordRow` hits all columns [here](https://github.com/celestiaorg/rsmt2d/pull/131/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688R191-R197) and `solveCrosswordCol` hits all rows [here](https://github.com/celestiaorg/rsmt2d/pull/131/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688R258-R264)

2022-09-28 22:11 UTC, musalbas commented
I see, I think I can see what the race condition is, but I think that might still not fix it. Suppose the last two rows to complete a column are being repaired, but they both call `noMissingData` before rebuilt shares are inserted into the square. Wouldn't `noMissingData` return false for both so the orthogonal row/col will never get verified? We should think about what would fix it fully - maybe applying a mutex over the entire second half of solveCrosswordRow/Col?

2022-09-30 23:26 UTC, adlerjohn reviewed
~#128 has been merged, maybe pull from default branch?~ Edit: wrong one, ignore.

2022-10-01 07:05 UTC, rahulghangas commented
> Suppose the last two rows to complete a column are being repaired, but they both call noMissingData before rebuilt shares are inserted into the square. Wouldn't noMissingData return false for both so the orthogonal row/col will never get verified?

I don't think so, because [here](https://github.com/celestiaorg/rsmt2d/pull/131/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L176) the `dataCol` of the eds gets mutated because [this](https://github.com/celestiaorg/rsmt2d/pull/131/files#diff-43b1ac1c622a799f2a850a10dee280ccfd5c04f315c69eb8848d215363dd8688L172) is returning a slice, not a copy. Since the mutex is on the column, whichever row completes the column will successfully call `noMissingData` on it

2022-10-02 15:25 UTC, musalbas commented
Oh that's a bug then, `col[r] = rebuiltShares[c]` is not supposed to mutate the the underlying DS. Assuming we fix that bug would the aforementioned issue exist and how can it be solved?

2022-10-02 15:31 UTC, musalbas commented
On another general note about the mutex - I think instead of adding rowColMutex to the EDS, we should define rowColMutex in solveCrossword and pass it as arguements to solveCrosswordRow/Col, because the mutex is only relevant to crossword solving.

Unless we think there's a way to fix this by making EDS itself entirely thread safe - but my current intuition is that even if EDS was thread safe the bug would still exist because it's a race condition in the crossword solver itself rather than the underlying EDS.

2022-10-04 14:02 UTC, rahulghangas commented
>On another general note about the mutex - I think instead of adding rowColMutex to the EDS, we should define rowColMutex in solveCrossword and pass it as arguements to solveCrosswordRow/Col, because the mutex is only relevant to crossword solving

Agreed, that would be better

>Unless we think there's a way to fix this by making EDS itself entirely thread safe - but my current intuition is that even if EDS was thread safe the bug would still exist because it's a race condition in the crossword solver itself rather than the underlying EDS

Yes, the issue exists regardless of whether EDS is thread safe or not

> maybe applying a mutex over the entire second half of solveCrosswordRow/Col
This seems like this would be the best way forward with the given implementation

2022-10-21 12:03 UTC, musalbas requested changes
instead of adding rowColMutex to the EDS, we should define rowColMutex in solveCrossword and pass it as arguements to solveCrosswordRow/Col, because the mutex is only relevant to crossword solving

2022-10-21 14:11 UTC, rahulghangas commented
Blocked by #134

2022-10-21 22:49 UTC, musalbas commented
Is there a reason why it's a single mutex now instead of one per row/col? Computing the Merkle root in computeSharesRoot takes up a significant chunk of the time so it would be ideal to parallelize that.

2022-10-22 05:43 UTC, rahulghangas commented
> I see, I think I can see what the race condition is, but I think that might still not fix it. Suppose the last two rows to complete a column are being repaired, but they both call noMissingData before rebuilt shares are inserted into the square. Wouldn't noMissingData return false for both so the orthogonal row/col will never get verified? We should think about what would fix it fully - maybe applying a mutex over the entire second half of solveCrosswordRow/Col?

We can't separate the insertion logic from the validation logic, since we get the race condition mentioned above

2023-06-20 19:11 UTC, rootulp commented
Going to close this b/c it doesn't appear to be actively being worked on.

2023-06-20 19:11 UTC, closed without merging